import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes'
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/svg+xml" href="/vectors/rose2.svg"/>
      </head>
      <body className={`antialiased min-h-screen flex flex-col bg-mid-900 dark:bg-mid-100`}>
        <ThemeProvider attribute="data-theme">
          <Header />
          <main className="flex-grow flex">
            <div className="container mx-auto px-4 flex flex-col gap-8 bg-light dark:bg-dark min-h-full">
              {children}    
            </div>
          </main>            
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
