import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes'
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import "./globals.css";

export const metadata: Metadata = {
  title: { default: 'A Tale of Thorns', template: '%s | A Tale of Thorns' },
  description: "Generated by create next app",
  openGraph: {
    siteName: 'A Tale of Thorns',
    images: [{ url: 'https://rose.fruitfolio.com/vectors/Rose.svg' }]
  },
  alternates: {
    canonical: 'https://rose.fruitfolio.com/archive',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/svg+xml" href="/vectors/rose2.svg" />
      </head>
      <body className={`antialiased min-h-screen flex flex-col bg-mid-900 dark:bg-mid-100 text-dark dark:text-light`}>
        <ThemeProvider attribute="data-theme">
          <Header />
          <main className="flex-grow flex flex-col">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
